### PR TITLE
Do not trim additional extra lines

### PR DESCRIPTION
**Pull request by gustavnikolaj**
Prompted by #8 

Semver major change.

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
@papandreou, can I trouble you for a review of this?

**Comment by papandreou** [comment]
@gustavnikolaj, yay, this is exactly what I need :tada:

Thanks a lot!

**Comment by gustavnikolaj** [comment]
Released with version 2.0.0 :-)

**Comment by papandreou** [comment]
Awesomeness! :rocket:

**Pull request merged**
