### PR TITLE
Use named exports exports, simplifying index.js

### PR DESCRIPTION
**Pull request by papandreou**
I'm not too familiar with ESM yet, so I'm not sure if default exports are somehow better than named ones -- but it seems like src/index.js can be simplified by using named exports :)

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
I see where you are going with this, but I think I prefer the export default behaviour for the specific imports:

```js
import qw from '@gustavnikolaj/string-utils/qw';
```

When there's only one thing being exported I think it makes more sense :-) But the code in index.js does not get pretty from it :)

You could argue wether the specific imports are necessary, but it at least allows you to use portions in a bundle without pulling in everything.

**Comment by gustavnikolaj** [comment]
(BTW sorry for the lint error on CI, I f'ed up the eslintignore files...)

**Comment by papandreou** [comment]
Fair enough, I didn't think about the case where you do a "deep `import`" :)

**Comment by papandreou** [comment]
... Although I guess `import { qw } from "@gustavnikolaj/string-util";` is also completely tree-shakeable, so would you ever need `import qw from "@gustavnikolaj/string-util/qw";`?

**Comment by gustavnikolaj** [comment]
I actually quite like your change. I think it does the right thing if you just also export the function as default.

```js
// deindent.js
export function deindent() { /* ... */ }
export default deindent;

//index.js
export * from "./deindent";

// in repl:
 string-utils on papandreou-feature/namedExports* $ node
> require('./')
{ deindent: [Getter] }
```

Unfortunately it doesn't work with the module.exports shim if you have both export default and a name export, it seems:

```
// in repl:
string-utils on papandreou-feature/namedExports* $ node
> require('./deindent')
{ deindent: [Function: deindent],
  default: [Function: deindent] }
```

Where as it used to be:

```
 string-utils on master $ node
> require('./deindent')
[Function: deindent]
```

**Comment by gustavnikolaj** [comment]
You're right. I think I went a bit overboard when adding those importable sub files like that.

It still seems to be the right thing (semantically at least) to `export default` the main thing in a file. But maybe I'm just too set in my ways.

Thanks for the PR and the suggestion, but I think I'll keep it as is for now :-)

**Pull request closed without merging**
